package pub.timelyrain.logmining.biz;

public class Constants {
    public static final String MINING_START = "begin SYS.DBMS_LOGMNR.START_LOGMNR(STARTSCN => ?, ENDSCN => ? ,OPTIONS =>  SYS.DBMS_LOGMNR.SKIP_CORRUPTION+SYS.DBMS_LOGMNR.NO_SQL_DELIMITER+SYS.DBMS_LOGMNR.NO_ROWID_IN_STMT+SYS.DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG + SYS.DBMS_LOGMNR.CONTINUOUS_MINE+SYS.DBMS_LOGMNR.COMMITTED_DATA_ONLY+SYS.DBMS_LOGMNR.STRING_LITERALS_IN_STMT);  end;";
    public static final String MINING_START_ENDLESS = "begin SYS.DBMS_LOGMNR.START_LOGMNR(STARTSCN => ? ,OPTIONS =>  SYS.DBMS_LOGMNR.SKIP_CORRUPTION+SYS.DBMS_LOGMNR.NO_SQL_DELIMITER+SYS.DBMS_LOGMNR.NO_ROWID_IN_STMT+SYS.DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG + SYS.DBMS_LOGMNR.CONTINUOUS_MINE+SYS.DBMS_LOGMNR.COMMITTED_DATA_ONLY+SYS.DBMS_LOGMNR.STRING_LITERALS_IN_STMT);  end;";
    public static final String MINING_END = "begin SYS.DBMS_LOGMNR.END_LOGMNR; end;";
    public static final String QUERY_REDO = "SELECT SCN, COMMIT_SCN, SEQUENCE#, TIMESTAMP, COMMIT_TIMESTAMP, OPERATION, SEG_OWNER, TABLE_NAME, ROW_ID, CSF, SQL_REDO FROM  V$LOGMNR_CONTENTS  WHERE OPERATION_CODE IN (1,2,3,5) ";
    public static final String QUERY_CURRENT_SCN = "select current_scn from v$database";
    public static final String QUEYR_TALBE_DICT = "SELECT OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,DATA_PRECISION,NULLABLE,(SELECT 'Y' FROM DBA_CONS_COLUMNS PKCOL INNER JOIN DBA_CONSTRAINTS PK ON PK.CONSTRAINT_NAME = PKCOL.CONSTRAINT_NAME AND PK.OWNER = PKCOL.OWNER WHERE PK.CONSTRAINT_TYPE = 'P' AND PK.OWNER = COL.OWNER AND PK.TABLE_NAME = COL.TABLE_NAME AND PKCOL.COLUMN_NAME = COL.COLUMN_NAME) AS PK FROM DBA_TAB_COLUMNS COL WHERE COL.OWNER = ? AND COL.TABLE_NAME = ?";

    public static final String MINING_START_BY_TIME = "begin SYS.DBMS_LOGMNR.START_LOGMNR(STARTTIME => to_date(?,'YYYYMMDDHH24MI'), ENDTIME => sysdate() ,OPTIONS =>  SYS.DBMS_LOGMNR.SKIP_CORRUPTION+SYS.DBMS_LOGMNR.NO_SQL_DELIMITER+SYS.DBMS_LOGMNR.NO_ROWID_IN_STMT+SYS.DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG + SYS.DBMS_LOGMNR.CONTINUOUS_MINE+SYS.DBMS_LOGMNR.COMMITTED_DATA_ONLY+SYS.DBMS_LOGMNR.STRING_LITERALS_IN_STMT);  end;";
    public static final String QUERY_MINING_START_SCN = "SELECT SCN FROM V$LOGMNR_CONTENTS WHERE COMMIT_SCN >= ? AND ROWNUM = 1";

}
