
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: 
    username: 
    password: 
    type: com.zaxxer.hikari.HikariDataSource

  rabbitmq:
    host: 
    port: 5672
    username: 
    password: 

  application:
    name: oracle-mining

  redis:
    host: 
    port: 
    password: 

logging:
  level:
    org:
      springframework: OFF
    #root: OFF
mining:
  #多租户模式 设置true 普通模式设置 false
  multiTenant: true


  #同步表名: 数据库用户名.数据库表名(大写不允许使用*通配)|交换机名称|取数规则(ECMA语法)可以为空,条件为true时不推送. 条件语句为js语法
  tables:
    - schema.table|oracle-sync-exchange-baseinfo


  exchanges:
    oracle-sync-exchange-biz:
      - oracle-sync.ciic-bsp-biz
    oracle-sync-exchange-baseinfo:
      - oracle-sync.ciic-bsp-cus
      - oracle-sync.ciic-bsp-biz
    oracle-sync-exchange-salary:
      - oracle-sync.ciic-bsp-wage
